import type { AnalyzedParam } from '@/lib/analyzers';

export const BADGE_LABEL: Record<AnalyzedParam['kind'], string> = {
  jwt: 'JWT',
  timestamp: 'Timestamp',
  uuid: 'UUID',
  base64: 'Base64',
  json: 'JSON',
  hash: 'Hash',
  color: 'Color',
  geo: 'Geo',
  xss: 'XSS Risk',
  sqli: 'SQL Injection',
  token_prefix: 'API Key',
  credential: 'Credential',
  db_connection: 'DB Connection',
  crypto: 'Crypto Wallet',
  'user-agent': 'User Agent',
  marketing: 'Marketing',
  pagination: 'Pagination',
  sort: 'Sort',
  oauth: 'OAuth',
  boolean: 'Boolean',
  network: 'IP',
  email: 'Email',
  phone: 'Phone',
  locale: 'Locale',
  currency: 'Currency',
  number: 'Number',
  semver: 'Semver',
  domain: 'Domain',
  mime: 'MIME',
  duration: 'Duration',
  hex: 'Hex',
  slug: 'Slug',
  cron: 'Cron',
  regex: 'Regex',
  file_path: 'File Path',
  authorization: 'Authorization',
  uri: 'URI',
};
